[package]
name = "day-04"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

#[lib]
#path = "src/lib.rs"

[dependencies]
glam = "0.24.2"
itertools = "0.12.0"

[lints]
workspace = true
